#!/bin/bash

usage() {
    echo "usage: `basename $0` [-i toy | -u toy] ..."
    exit 1
}

start_toybox_install() (
    if [ ! -d "$1" ]; then
        echo "no (`pwd`)"
        exit 3
    fi

    cd -P "$1" && toybox_install
)

start_toybox_uninstall() (
    if [ ! -d "$1" ]; then
        echo "no (`pwd`)"
        exit 3
    fi

    cd -P $1 && toybox_uninstall
)

start() {
    if [ $# = 0 ]; then usage; fi

    if ! . .toybox.conf; then
        echo 'um'
        exit 2
    fi

    while getopts :i:u: OPTIONS; do
        case $OPTIONS in
            i)
                start_toybox_install $OPTARG
                ;;
            u)
                start_toybox_uninstall $OPTARG
                ;;
            *)
                usage
        esac
    done

    shift $((OPTIND-1))

    if [ ! $# = 0 ]; then usage; fi
}

start $@ #2> /dev/null
